#pragma once

// Valeurs typiques pour ESP32-P4
#ifndef ISP_AE_BLOCK_X_NUM
#define ISP_AE_BLOCK_X_NUM 16
#endif

#ifndef ISP_AE_BLOCK_Y_NUM
#define ISP_AE_BLOCK_Y_NUM 16
#endif

#ifndef ISP_HIST_SEGMENT_NUMS
#define ISP_HIST_SEGMENT_NUMS 16
#endif

#ifndef ISP_BF_TEMPLATE_X_NUMS
#define ISP_BF_TEMPLATE_X_NUMS 5
#endif

#ifndef ISP_BF_TEMPLATE_Y_NUMS
#define ISP_BF_TEMPLATE_Y_NUMS 5
#endif

#ifndef ISP_SHARPEN_TEMPLATE_X_NUMS
#define ISP_SHARPEN_TEMPLATE_X_NUMS 3
#endif

#ifndef ISP_SHARPEN_TEMPLATE_Y_NUMS
#define ISP_SHARPEN_TEMPLATE_Y_NUMS 3
#endif

#ifndef ISP_GAMMA_CURVE_POINTS_NUM
#define ISP_GAMMA_CURVE_POINTS_NUM 16
#endif

#ifndef ISP_CCM_DIMENSION
#define ISP_CCM_DIMENSION 3
#endif

#ifndef ISP_SHARPEN_HIST_INTERVAL_NUMS
#define ISP_SHARPEN_HIST_INTERVAL_NUMS 16
#endif
