# Configuration RTSP Server pour OV5647
# ESP32-P4 avec encodeur H.264 hardware

substitutions:
  device_name: "esp32-p4-camera"
  friendly_name: "ESP32-P4 RTSP Camera"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-p4-function-ev-board
  variant: esp32p4
  flash_size: 32MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    version: 5.4.2
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
    advanced:
      enable_idf_experimental_features: true
      loop_task_stack_size: 16384       # 16KB pour loopTask (défaut 8192)
      compiler_optimization: PERF       # Optimize for performance (not size)
      enable_lwip_tcpip_core_locking: true  # Improve socket performance by 20-200%
      sdkconfig_options:
        # SPIRAM configuration
        CONFIG_SPIRAM_USE_CAPS_ALLOC: y
        CONFIG_SPIRAM_USE_MALLOC: y
        # File system configuration
        CONFIG_FATFS_LFN_STACK: "y"
        CONFIG_VFS_MAX_COUNT: "16"        # Augmenter de 8 à 16
        CONFIG_VFS_SUPPORT_IO: "y"
        # Network configuration
        CONFIG_LWIP_SO_RCVBUF: "y"
        CONFIG_LWIP_MAX_SOCKETS: "16"     # Plus de sockets réseau
        # Stack sizes pour les tasks système
        CONFIG_ESP_MAIN_TASK_STACK_SIZE: "16384"       # 16KB (était 3.5KB)
        CONFIG_FREERTOS_IDLE_TASK_STACKSIZE: "2048"    # 2KB (était 1.5KB)
        CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: "4096" # 4KB

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional: Enable fallback hotspot
  ap:
    ssid: "${device_name} Fallback"
    password: "fallback123"

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API (optional)
api:
  encryption:
    key: !secret api_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# I2C Bus for camera sensor
i2c:
  - id: bsp_bus
    sda: GPIO14
    scl: GPIO13
    scan: true

# MIPI CSI Camera - OV5647
mipi_dsi_cam:
  id: main_camera
  i2c_id: bsp_bus
  sensor_type: ov5647      # Votre caméra détectée
  sensor_addr: 0x36        # Adresse I2C OV5647
  resolution: 800x600      # Résolution adaptée pour écran 1024x600
  pixel_format: RGB565     # RGB565 works better than YUYV with OV5647
  framerate: 30            # 30 FPS

  # Bayer pattern for OV5647
  raw_type: RAW8
  bayer_type: GBRG

# Switches to control streaming servers
switch:
  - platform: template
    name: "RTSP Server"
    id: rtsp_enable_switch
    restore_mode: RESTORE_DEFAULT_OFF  # OFF au démarrage
    optimistic: true
    turn_on_action:
      - lambda: |-
          auto *rtsp = id(rtsp_srv);
          if (rtsp != nullptr) {
            rtsp->set_enabled(true);
          }
    turn_off_action:
      - lambda: |-
          auto *rtsp = id(rtsp_srv);
          if (rtsp != nullptr) {
            rtsp->set_enabled(false);
          }

  - platform: template
    name: "Camera Web Server"
    id: web_camera_enable_switch
    restore_mode: RESTORE_DEFAULT_OFF  # OFF au démarrage
    optimistic: true
    turn_on_action:
      - lambda: |-
          auto *web_cam = id(web_cam_srv);
          if (web_cam != nullptr) {
            web_cam->set_enabled(true);
          }
    turn_off_action:
      - lambda: |-
          auto *web_cam = id(web_cam_srv);
          if (web_cam != nullptr) {
            web_cam->set_enabled(false);
          }

  - platform: template
    name: "LVGL Camera Display"
    id: lvgl_display_enable_switch
    restore_mode: RESTORE_DEFAULT_OFF  # OFF au démarrage
    optimistic: true
    turn_on_action:
      - lambda: |-
          auto *lvgl_disp = id(lvgl_cam_display);
          if (lvgl_disp != nullptr) {
            lvgl_disp->set_enabled(true);
          }
    turn_off_action:
      - lambda: |-
          auto *lvgl_disp = id(lvgl_cam_display);
          if (lvgl_disp != nullptr) {
            lvgl_disp->set_enabled(false);
          }

# RTSP Server avec encodeur H.264 hardware
rtsp_server:
  id: rtsp_srv
  camera_id: main_camera
  port: 554                # Port RTSP standard
  stream_path: "/stream"   # URL: rtsp://<IP>:554/stream

  # Authentification RTSP
  username: "youkorr"
  password: "youkorr123"
  # URL avec auth: rtsp://youkorr:youkorr123@<IP>:554/stream

  # Paramètres encodeur H.264 hardware
  bitrate: 2000000         # 2 Mbps (recommandé pour 800x600)
  gop: 30                  # GOP de 30 frames (1 keyframe/sec @ 30fps)
  qp_min: 10               # Qualité minimale
  qp_max: 40               # Qualité maximale

  # Réseau
  rtp_port: 5004           # Port RTP
  rtcp_port: 5005          # Port RTCP
  max_clients: 3           # Maximum 3 clients simultanés

# Camera Web Server (MJPEG streaming via HTTP)
camera_web_server:
  id: web_cam_srv
  camera_id: main_camera
  port: 8080               # Port HTTP pour le stream MJPEG
                           # URL: http://<IP>:8080/

# Web server pour monitoring (optionnel)
web_server:
  port: 80

# Status LED (optionnel)
# Configurez selon votre board
# status_led:
#   pin: GPIO45
