#pragma once

#include "esphome/core/component.h"
#include "esphome/core/automation.h"
#include "esphome/core/helpers.h"
#include "esphome/components/esp32_camera/esp32_camera.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"

#include <functional>
#include <list>
#include <memory>
#include <string>
#include <vector>

// Forward decl - ESP-DL types stay opaque in the public header
namespace dl {
namespace image {
struct img_t;
class ImagePreprocessor;
}
namespace detect {
class yolo11PostProcessor;
struct result_t;
}
class Model;
}

namespace esphome {
namespace yolov11 {

// COCO detection result returned by ESP-DL.
struct DetectionBox {
  int x1, y1, x2, y2;
  float score;
  int category;       // 0..79 COCO index
  const char *label;  // pointer into the static COCO_CLASSES table
};

// Listener interface used by the text_sensor sub-platform.
class YOLOv11Listener {
 public:
  virtual ~YOLOv11Listener() = default;
  virtual void on_detections(const std::vector<DetectionBox> &detections,
                              const std::string &summary) = 0;
};


class YOLOv11Component : public Component {
 public:
  // ---------- ESPHome lifecycle ----------
  void setup() override;
  void loop() override;
  void dump_config() override;
  float get_setup_priority() const override { return setup_priority::LATE; }

  // ---------- YAML setters ----------
  void set_camera(esp32_camera::ESP32Camera *cam) { this->camera_ = cam; }
  void set_score_threshold(float v) { this->score_threshold_ = v; }
  void set_nms_threshold(float v) { this->nms_threshold_ = v; }
  void set_detection_interval_ms(int v) { this->detection_interval_ms_ = v; }
  void set_max_detections(int v) { this->max_detections_ = v; }
  void set_inference_task_stack_size(int v) { this->task_stack_size_ = v; }
  void set_inference_task_priority(int v) { this->task_priority_ = v; }

  // Model-from-file path (alternative to flash-rodata embed).
  // The buffer pointer is the C++ id generated by jesserockz's `file:`
  // platform - a `const uint8_t[N]` decays to `const uint8_t*`. The size
  // is computed at codegen time from the on-disk file and passed here.
  void set_model_buffer(const uint8_t *data, size_t size) {
    this->external_model_data_ = data;
    this->external_model_size_ = size;
  }

  // ---------- triggers / listeners ----------
  void add_on_object_detected_callback(std::function<void(int, std::string)> cb) {
    this->on_object_detected_callbacks_.push_back(std::move(cb));
  }
  void add_listener(YOLOv11Listener *l) { this->listeners_.push_back(l); }

  // ---------- public API ----------
  // Force a one-shot inference on the most recently captured frame.
  void trigger_inference();

  // Get current cached detections. Mutex-protected.
  std::vector<DetectionBox> get_detections();
  int get_detected_count();
  std::string get_last_summary() const { return this->last_summary_; }

 protected:
  // Background inference task.
  static void inference_task_trampoline(void *arg);
  void inference_task_loop_();
  bool initialise_detector_();
  void run_one_inference_();

  // Helper: build a "label:score%,..." summary string.
  static std::string build_summary_(const std::vector<DetectionBox> &dets, int max_items);

  // ---------- members ----------
  esp32_camera::ESP32Camera *camera_{nullptr};

  // External model buffer (set when model_id: is provided).
  const uint8_t *external_model_data_{nullptr};
  size_t external_model_size_{0};

  float score_threshold_{0.30f};
  float nms_threshold_{0.50f};
  int detection_interval_ms_{200};
  int max_detections_{10};
  int task_stack_size_{8192};
  int task_priority_{5};

  // ESP-DL state - opaque in the public header. The actual type is
  // `YOLO11Detect *` but we hide it behind dl::Model* so the header
  // only depends on already-forward-declared ESP-DL classes.
  dl::Model *model_{nullptr};
  bool model_ready_{false};

  // Single-slot frame queue. The camera callback updates these; the
  // inference task reads them when signalled. We only keep the LATEST
  // frame, dropping older ones if the inference is slower than the
  // camera (matches what M5Stack/Espressif do in the BSP demos).
  uint8_t *pending_frame_data_{nullptr};
  size_t pending_frame_size_{0};
  uint32_t last_inference_ms_{0};

  TaskHandle_t inference_task_handle_{nullptr};
  SemaphoreHandle_t frame_signal_{nullptr};
  SemaphoreHandle_t state_mutex_{nullptr};

  std::vector<DetectionBox> cached_detections_;
  std::string last_summary_;

  std::vector<std::function<void(int, std::string)>> on_object_detected_callbacks_;
  std::vector<YOLOv11Listener *> listeners_;
};


// =====================================================================
// Trigger fired after each detection pass (count + summary string).
// Exposed in YAML as both `on_object_detected:` and `on_detection:`
// (same trigger class, two yaml keys).
// =====================================================================
class ObjectDetectedTrigger : public Trigger<int, std::string> {
 public:
  explicit ObjectDetectedTrigger(YOLOv11Component *parent) {
    parent->add_on_object_detected_callback(
        [this](int count, std::string summary) {
          this->trigger(count, std::move(summary));
        });
  }
};


// =====================================================================
// Action: yolov11.inference - force a one-shot inference now.
// =====================================================================
template<typename... Ts>
class RunInferenceAction : public Action<Ts...>, public Parented<YOLOv11Component> {
 public:
  void play(Ts... x) override { this->parent_->trigger_inference(); }
};


}  // namespace yolov11
}  // namespace esphome
