/*
 * SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: ESPRESSIF MIT
 */

#include "esp_cam_sensor_detect.h"
#include "esp_cam_sensor.h"

/**
 * @brief Stub implementation of camera sensor detect function array symbols
 *
 * In ESP-IDF build system, these symbols are generated by linker fragments (.lf files).
 * For PlatformIO/ESPHome which doesn't process linker fragments, we provide them manually.
 *
 * The auto-detection code in esp_video_init.c iterates:
 *   for (esp_cam_sensor_detect_fn_t *p = &__esp_cam_sensor_detect_fn_array_start;
 *        p < &__esp_cam_sensor_detect_fn_array_end; ++p)
 *
 * We create a contiguous array and make the _start and _end symbols point to
 * the first element and one-past-the-last element.
 *
 * NOTE: Pour utiliser un capteur avec une adresse I2C différente, modifiez
 *       le champ .sccb_addr ci-dessous:
 *       - SC202CS: 0x36 (par défaut)
 *       - OV5647: 0x36
 *       - Autres capteurs: consultez la datasheet
 *
 * Pour ajouter plusieurs capteurs à détecter automatiquement, décommentez
 * les entrées supplémentaires ci-dessous.
 */

// Forward declarations of sensor detection functions
extern esp_cam_sensor_device_t *sc202cs_detect(void *config);
extern esp_cam_sensor_device_t *ov5647_detect(void *config);
extern esp_cam_sensor_device_t *ov02c10_detect(void *config);

// Sensor detection array - tous les capteurs compilés
// L'auto-détection essaiera chaque capteur dans l'ordre jusqu'à trouver celui qui répond
//
// TOUS les capteurs sont essayés automatiquement:
// 1. SC202CS (adresse I2C 0x30)
// 2. OV5647 (adresse I2C 0x36)
// 3. OV02C10 (adresse I2C 0x3C)
//
// Si vous changez de ESP32-P4 avec un capteur différent, l'auto-détection
// trouvera automatiquement le bon capteur sans modification du code!

// Utiliser l'attribut section pour garantir que ces structures sont placées consécutivement
__attribute__((section(".sensor_detect_array"))) __attribute__((used))
esp_cam_sensor_detect_fn_t __esp_cam_sensor_detect_fn_array_start = {
    .port = ESP_CAM_SENSOR_MIPI_CSI,
    .sccb_addr = 0x30,  // SC202CS
    .detect = sc202cs_detect,
};

__attribute__((section(".sensor_detect_array"))) __attribute__((used))
static esp_cam_sensor_detect_fn_t __esp_cam_sensor_entry_1 = {
    .port = ESP_CAM_SENSOR_MIPI_CSI,
    .sccb_addr = 0x36,  // OV5647
    .detect = ov5647_detect,
};

__attribute__((section(".sensor_detect_array"))) __attribute__((used))
static esp_cam_sensor_detect_fn_t __esp_cam_sensor_entry_2 = {
    .port = ESP_CAM_SENSOR_MIPI_CSI,
    .sccb_addr = 0x3c,  // OV02C10
    .detect = ov02c10_detect,
};

// End marker - également dans la même section pour être consécutif
__attribute__((section(".sensor_detect_array"))) __attribute__((used))
esp_cam_sensor_detect_fn_t __esp_cam_sensor_detect_fn_array_end;
