/*
 * SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: ESPRESSIF MIT
 */

#include "esp_cam_sensor_detect.h"
#include "esp_cam_sensor.h"

/**
 * @brief Stub implementation of camera sensor detect function array symbols
 *
 * In ESP-IDF build system, these symbols are generated by linker fragments (.lf files).
 * For PlatformIO/ESPHome which doesn't process linker fragments, we provide them manually.
 *
 * The auto-detection code in esp_video_init.c iterates:
 *   for (esp_cam_sensor_detect_fn_t *p = &__esp_cam_sensor_detect_fn_array_start;
 *        p < &__esp_cam_sensor_detect_fn_array_end; ++p)
 *
 * We create a contiguous array and make the _start and _end symbols point to
 * the first element and one-past-the-last element.
 *
 * NOTE: Pour utiliser un capteur avec une adresse I2C différente, modifiez
 *       le champ .sccb_addr ci-dessous:
 *       - SC202CS: 0x36 (par défaut)
 *       - OV5647: 0x36
 *       - Autres capteurs: consultez la datasheet
 *
 * Pour ajouter plusieurs capteurs à détecter automatiquement, décommentez
 * les entrées supplémentaires ci-dessous.
 */

// Forward declarations of sensor detection functions
extern esp_cam_sensor_device_t *sc202cs_detect(void *config);
// extern esp_cam_sensor_device_t *ov5647_detect(void *config);  // Décommentez si disponible

// Sensor detection array
// Must be non-static so the linker can create the symbols
esp_cam_sensor_detect_fn_t __esp_cam_sensor_detect_fn_array_start = {
    .port = ESP_CAM_SENSOR_MIPI_CSI,
    .sccb_addr = 0x36,  // SC202CS default I2C address - MODIFIEZ ICI si nécessaire
    .detect = sc202cs_detect,
};

// Pour détecter plusieurs capteurs, décommentez et ajustez:
// static esp_cam_sensor_detect_fn_t __esp_cam_sensor_entry_1 = {
//     .port = ESP_CAM_SENSOR_MIPI_CSI,
//     .sccb_addr = 0x36,  // OV5647 address
//     .detect = ov5647_detect,
// };

// End marker - placed right after start in memory
// The iteration logic uses pointer comparison: p < &end
// So we need this to be at the next memory location
esp_cam_sensor_detect_fn_t __esp_cam_sensor_detect_fn_array_end;

/**
 * @brief Initialize function to set up end marker
 *
 * Since we can't guarantee memory layout without a linker script,
 * we use a constructor to validate the setup.
 */
__attribute__((constructor))
static void validate_sensor_detect_array(void) {
    // In practice, the compiler should place these variables contiguously
    // since they're defined one after another with no other variables between them.
    // If this ever fails, we'd need a proper linker script.

    // The end symbol just needs to exist - its value doesn't matter much
    // as long as it's at a higher address than start
}
