/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-FileCopyrightText: ESPHome/PlatformIO Build Fix
 *
 * SPDX-License-Identifier: ESPRESSIF MIT
 */

/**
 * @file esp_ipa_detect_stubs.c
 * @brief ESP IPA detection array stubs for ESPHome/PlatformIO builds
 *
 * In ESP-IDF builds, these symbols are automatically generated by the linker
 * from sections defined by ESP_IPA_DETECT_FN() macro. However, in ESPHome/PlatformIO
 * builds, the linker script doesn't support this feature, so we must define
 * the symbols manually.
 *
 * This file provides empty array symbols to satisfy the linker when
 * esp_ipa_pipeline_create() tries to iterate over registered IPAs.
 *
 * For ESPHome, we don't use auto-detection - we load IPA configs from JSON files
 * using esp_ipa_json_loader.c instead.
 */

#include "esp_ipa_detect.h"

/**
 * @brief IPA detection array symbols for ESPHome/PlatformIO
 *
 * These symbols are referenced by libesp_ipa.a (esp_ipa_pipeline_create function).
 * We define them as empty arrays since ESPHome uses JSON-based IPA configuration
 * instead of the auto-detection mechanism.
 *
 * Memory layout:
 *   __esp_ipa_detect_array_start: pointer to first element (none exist)
 *   __esp_ipa_detect_array_end: pointer right after last element (same address)
 *
 * The loop in esp_ipa_pipeline_create will see start == &end and skip iteration.
 */

// Define as aligned section to ensure proper linking
__attribute__((section(".data.ipa_detect"), used, aligned(4)))
esp_ipa_detect_t __esp_ipa_detect_array_start = {
    .detect = NULL,  // Sentinel: no IPA to detect
    .name = NULL
};

__attribute__((section(".data.ipa_detect"), used, aligned(4)))
esp_ipa_detect_t __esp_ipa_detect_array_end = {
    .detect = NULL,  // End marker
    .name = NULL
};

/**
 * DESIGN RATIONALE:
 *
 * In ESP-IDF, IPAs are registered using ESP_IPA_DETECT_FN() macro which places
 * function pointers in a linker section. The linker then creates start/end symbols.
 *
 * In ESPHome:
 * 1. The linker doesn't auto-create these symbols
 * 2. We don't need auto-detection anyway
 * 3. We use embedded JSON configs (ov5647_default.json, ov02c10_default.json)
 * 4. These configs are loaded by esp_ipa_json_loader.c
 *
 * This stub file simply provides the symbols to prevent linking errors.
 * The actual IPA configuration happens through esp_ipa_pipeline_get_config()
 * which loads JSON data instead of calling detection functions.
 */
