/*
 * SPDX-FileCopyrightText: 2024-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: ESPRESSIF MIT
 */

#include "esp_ipa_types.h"

/**
 * @brief Stub implementation of IPA detection array symbols
 *
 * In ESP-IDF, these symbols are generated by linker fragments (.lf files).
 * For PlatformIO/ESPHome, we provide them manually.
 *
 * The IPA pipeline code iterates: for (p = &start; p < &end; ++p)
 *
 * Available IPAs in libesp_ipa.a:
 * - AWB: Auto White Balance (Gray World)
 * - AGC: Auto Gain Control (Threshold)
 * - Denoising: Gain feedback
 * - Sharpen: Frequency feedback
 * - Gamma: Luminance feedback
 * - CC: Color Correction (Linear)
 */

// Forward declarations from libesp_ipa.a
extern esp_ipa_t *__esp_ipa_detect_fn_awb_gray_world(void *config);
extern esp_ipa_t *__esp_ipa_detect_fn_agc_threshold(void *config);
extern esp_ipa_t *__esp_ipa_detect_fn_denoising_gain_feedback(void *config);
extern esp_ipa_t *__esp_ipa_detect_fn_sharpen_freq_feedback(void *config);
extern esp_ipa_t *__esp_ipa_detect_fn_gamma_lumma_feedback(void *config);
extern esp_ipa_t *__esp_ipa_detect_fn_cc_linear(void *config);

// Define the structure type used for detection
typedef struct esp_ipa_detect {
    const char *name;
    esp_ipa_t *(*detect)(void *);
} esp_ipa_detect_t;

/**
 * IPA detection array
 *
 * The library expects &__esp_ipa_detect_array_start and &__esp_ipa_detect_array_end
 * We create the array and use the first and last+1 elements as those symbols
 */
esp_ipa_detect_t __esp_ipa_detect_array_start = {
    .name = "awb_gray_world",
    .detect = __esp_ipa_detect_fn_awb_gray_world,
};

// Additional IPA entries placed consecutively
static esp_ipa_detect_t __esp_ipa_entry_1 = {
    .name = "agc_threshold",
    .detect = __esp_ipa_detect_fn_agc_threshold,
};

static esp_ipa_detect_t __esp_ipa_entry_2 = {
    .name = "denoising_gain_feedback",
    .detect = __esp_ipa_detect_fn_denoising_gain_feedback,
};

static esp_ipa_detect_t __esp_ipa_entry_3 = {
    .name = "sharpen_freq_feedback",
    .detect = __esp_ipa_detect_fn_sharpen_freq_feedback,
};

static esp_ipa_detect_t __esp_ipa_entry_4 = {
    .name = "gamma_lumma_feedback",
    .detect = __esp_ipa_detect_fn_gamma_lumma_feedback,
};

static esp_ipa_detect_t __esp_ipa_entry_5 = {
    .name = "cc_linear",
    .detect = __esp_ipa_detect_fn_cc_linear,
};

// End marker
esp_ipa_detect_t __esp_ipa_detect_array_end;
